[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store && npm run build"
  publish = "build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../../packages/land-model/ ../../packages/map/"
