[build]
  command = "pnpm run build"
  publish = "build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../../packages/land-model/ ../../packages/map/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    # Allows sandboxed iframe to be embedded into any site
    Access-Control-Allow-Origin = "*"
